### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by ma-sadeghi** [scikit-fmm/scikit-fmm#65]
Could you please add support for Python 3.10 as well? Many thanks!

**Comment by jkfurtney** [comment]
Hi and thanks for getting in touch. This is related to #64

scikit-fmm should work with Python 3.10 if you build from source. Are you getting a specific error message when you try scikit-fmm with Python 3.10?

**Comment by ma-sadeghi** [comment]
Thanks for your reply. I've never tried building from source, but since `scikit-fmm` is a dependency for our package ([porespy](https://github.com/PMEAL/porespy/)), we rely on it to be pip-installable. Here's the error from the CI:

```
 Pinned packages:
  - python 3.10.*

Encountered problems while solving:
  - package scikit-fmm-2019.1.30-py39hd56b5f2_3 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
```

Reference to the CI log: https://github.com/PMEAL/porespy/runs/4679056301?check_suite_focus=true

**Comment by xylar** [comment]
For more context, it appears not to be  building on conda-forge with Python 3.10:
https://github.com/conda-forge/scikit-fmm-feedstock/pull/18

**Comment by jkfurtney** [comment]
I just regenerated the cython wrapper code in pheap.cpp, that may fix the issue, let me know how you get on.

**Comment by jkfurtney** [comment]
I tried a local build on Ubuntu 20.04 with the Python 3.10 from the deadsnakes ppa and I get the same problem:

```In file included from /usr/include/python3.10/Python.h:74,
                 from skfmm/pheap.cpp:4:
skfmm/pheap.cpp: In function ‘void __pyx_tp_dealloc_5skfmm_5pheap_pheap(PyObject*)’:
/usr/include/python3.10/object.h:133:58: error: lvalue required as increment operand
  133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
      |                                                          ^
skfmm/pheap.cpp:1910:7: note: in expansion of macro ‘Py_REFCNT’
 1910 |     ++Py_REFCNT(o);
      |       ^~~~~~~~~
/usr/include/python3.10/object.h:133:58: error: lvalue required as decrement operand
  133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
      |                                                          ^
skfmm/pheap.cpp:1912:7: note: in expansion of macro ‘Py_REFCNT’
 1912 |     --Py_REFCNT(o);```

It looks like this is related to cython.

**Comment by jkfurtney** [comment]
OK when I regenerated the cython bindings in pheap.cpp using cython 0.29.27 I was able to build with Python 3.10.2 and all the tests pass. I will get a release out later today.

**Comment by xylar** [comment]
That's awesome, thanks @jkfurtney!
