### ISSUE TITLE
Linux build broken in master

### ISSUE THREAD

**Issue by jkfurtney** [scikit-fmm/scikit-fmm#46]
skfmm/travel_time_marcher.cpp:92:9: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
         auto ret = tempset.insert(ind);
         ^
skfmm/travel_time_marcher.cpp:92:14: error: ‘ret’ does not name a type
         auto ret = tempset.insert(ind);
              ^
skfmm/travel_time_marcher.cpp:93:13: error: ‘ret’ was not declared in this scope
         if(!ret.second) continue; //avoid recursive call on identical parameter
             ^
error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -Iskfmm -I/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/numpy/core/include -I/opt/python/3.7.1/include/python3.7m -I/opt/python/3.7.1/include/python3.7m -c skfmm/travel_time_marcher.cpp -o build/temp.linux-x86_64-3.7/skfmm/travel_time_marcher.o -MMD -MF build/temp.linux-x86_64-3.7/skfmm/travel_time_marcher.o.d" failed with exit status 1
The command "python setup.py develop" failed and exited with 1 during .
Your build has been stopped.

**Comment by jkfurtney** [comment]
Works in Ubuntu LTS 20.04 and Python 3.8 gcc 9.3.0, failing on TravisCI
